name: Partigon
version: '${version}'
main: com.github.gameoholic.partigon.PartigonPlugin
api-version: 1.20
authors: [ Gameoholic ]
description: Test
commands:
  test:
    description: Test
    usage: /test
