name: '$name'
version: '$version'
main: com.github.gameoholic.partigon.PartigonPlugin
description: '$description'
api-version: '$apiVersion'
authors:
  - Gameoholic
commands:
  test:
    description: Test
    usage: /test
